class GhLensError(Exception): ...
class AuthError(GhLensError): ...
class ApiError(GhLensError): ...
class RateLimitError(ApiError): ...
class NetworkError(GhLensError): ...
class RepoNotFoundError(GhLensError): ...
